# Starter pipeline 
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:

  ### Variables ###
  serviceNamespace: $(SERVICE_NAMESPACE)
  repoPrefix: '$(REPO_PREFIX)'


stages:  
  #### Deploy All Images Stagee ####
  - stage: Deploy_All_Images
    jobs:
      - job: Change_Request 
        displayName : 'Change Control ServiceNow'
        pool : server
        steps:
          - task: InvokeRESTAPI@1
            displayName: "Quality Gate check with SerivceNow"
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'ServiceNow Loomsales demo for Schweiz'
              method: 'POST'
              body: |
                { 
                   "buildNumber": "$(build.buildId)",
                   "isMultiBranch": "true",
                   "branchName": "$(build.sourceBranchName)"
                }
              waitForCompletion: 'true'         
      - job: Deploy_All_Images
        pool:
           vmImage: ubuntu-latest
        steps:
          - task: HelmDeploy@0
            displayName: 'Deploying All Images'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'olympus'
              chartName: 'boutique'
              releaseName: 'boutique'
              chartType: FilePath
              chartPath: helm
              command: 'upgrade'
              force: true
              namespace: $(serviceNamespace)
              arguments: --set imageRepo=$(repoPrefix)
